### ISSUE TITLE
incorrect requirement

### ISSUE THREAD

**Issue by pavelsokolov** [moodleou/moodle-mod_subpage#21]
There's no 'sharedsubpage', while it's required. This is simply incorrect, since it assumes there's another copy of the subpage plugin.

https://github.com/moodleou/moodle-mod_subpage/blob/a5d0c470ea782f8efffa1997785f018f48f197d7/renderer.php#L27

**Comment by sammarshallou** [comment]
Ugh, who did that (don't answer that, I can see it and I know who the guilty part is). You're right, this is a bug - there shouldn't be a reference to that module which is not public.

**Comment by sammarshallou** [comment]
OK - I have fixed this and the fix is now in the 'master' and MOODLE_36_STABLE, MOODLE_35_STABLE github branches. For technical reasons it's not in MOODLE_37_STABLE yet, hopefully we will get that one updated soon (feel free to add a comment here if we forget). Please check it out using the new code and hopefully it works now, or at least won't fail for that reason...
