### ISSUE TITLE
Uitzondering - Class "format_studyplan\last_gasp" not found

### ISSUE THREAD

**Issue by juancarlos-galdos** [moodleou/moodle-mod_subpage#22]
Hello, 
I'm getting this error after installing this plugin in Moodle 4.2. Any solution?
Best regards

**Comment by Buda9** [comment]
Same here. I guess it needs custom course format for this plugin to work. As far as I could see, author didn't share that plugin with the community

**Comment by sammarshallou** [comment]
Hi, I'm sorry I missed this issue when originally reported, it probably came at a time when I couldn't keep up with email.

This plugin is reaching end of life and will not be supported through many more Moodle versions (I think there are some core and plugin course formats from other people that are fully supported and can do similar things), but I hadn't realised we broke this. The 'last_gasp' code is used to avoid deprecation warnings since Moodle 4.0 - it's a copy-paste of core code that has been deprecated, but without the warnings - but I have made a change so that, if not available, it calls the core code.

I'll edit the plugin page on the plugins directory to warn about the expected end of life (I don't know exactly when, I guess it will still work in 4.3 but maybe not 4.4).

This should be resolved now in our 'master' branch. Because of how we do release management, it won't change in our MOODLE_42_STABLE branch until our next quarterly release, which is next month.
